Various small improvements.
git-svn-id: https://svn.code.sf.net/p/freedos-32/code/trunk@443 85e9c19b-ca11-0410-bd92-afdf7feba87b

diff --git a/apps/newlib-port/patch-n-build b/apps/newlib-port/patch-n-build
--- a/apps/newlib-port/patch-n-build
+++ b/apps/newlib-port/patch-n-build
@@ -4,18 +4,27 @@
 pb_cwd=`pwd`
 invoc_path=$0
 
-case "$invoc_path" in
-# absolute path
-/*)
-	;;
-# relative path
-*)
-	invoc_path="${pb_cwd}/$invoc_path" ;;
-esac
+fix_path()
+{
+	local local_p
+	eval local_p=\$$1
+	case "$local_p" in
+	# absolute path
+	/*)
+		;;
+	# relative path
+	*)
+		local_p="${pb_cwd}/$local_p" ;;
+	esac
+	$local_p=`echo "$local_p" | sed 's/\/\//\//g; s/\/\.\//\//g; s/\/[^\/]*\/\.\.\//\//g'`
+	eval $1=\$local_p
+}
 
-if test ! -e "$invoc_path"
+fix_path invoc_path
+
+if test ! -f "$invoc_path"
 then
-	echo "$invoc_path not found!"
+	echo "[pb]$invoc_path not found!"
 	# lets try pwd and hope for the best
 	pb_dir=$pb_cwd
 else
@@ -23,11 +32,12 @@ else
 	pb_dir=`echo "$invoc_path" | sed 's/\/[^\/]*$/\//'`
 fi
 
+
 file_present1()
 {
 	if test ! -e "$1"
 	then
-		echo "Error: $1 not found"
+		echo "[pb]Error: file $1 not found"
 		exit 1
 	fi
 }
@@ -42,6 +52,7 @@ file_present1 "${pb_dir}/diffs/configure.diff"
 arch_file=
 nl_src_dir=
 dest_dir=
+temp_dir=
 remove_tmp_dir="yes"
 config_newlib="yes"
 make_nelib="yes"
@@ -65,12 +76,13 @@ Options:
 			(The name of the file is probably 
 			\"newlib-1.13.0.tar.bz\" or simmilar.)
 --dest-dir=DIR		copy library files to DIR
+--temp-dir=DIR		where to place temporary directory
 --no-remove		do not remove temporary directory
 --no-build		do not run configure or make
 --no-make		run configure but not make
---patch-makefile	patch Makefile
---make-once		do not patch and execute Makefile a second time to
-			to obtain libc without debug info
+--patch-makefile	patch Makefile in stead of making links
+--make-once		do not modify and execute Makefile a second time
+			to obtain a smaller libc without debug info
 --target=TARGET		buid for TARGET. (i586-pc-fd32 default)"
 
 # parse command line options
@@ -84,6 +96,8 @@ do
 		nl_src_dir=`echo "$pb_option" | sed 's/--source-dir=//'` ;;
 	--dest-dir=*)
 		dest_dir=`echo "$pb_option" | sed 's/--dest-dir=//'` ;;
+	--temp-dir=*)
+		temp_dir=`echo "$pb_option" | sed 's/--temp-dir=//'` ;;
 	--help | -help | help | -h)
 		echo "$pb_help"
 		exit 0
@@ -106,7 +120,7 @@ do
 	--target=*)
 		pb_target=`echo "$pb_option" | sed 's/--target=//'` ;;
 	*)
-		echo "Error: Syntax error in argument: $pb_option"
+		echo "[pb]Error: Syntax error in argument: $pb_option"
 		exit 1
 		;;
 	esac
@@ -115,21 +129,25 @@ done
 # find newlib sources
 if test -n "$arch_file"
 then
+	fix_path arch_file
+	echo "[pb]Archive file \"${arch_file}\" specified by user"
 	case "$arch_file" in
 	*.tar.gz)
 		;;
 	*)
-		echo "Error: file must be a \".tar.gz\" file"
-		echo "Error: $arch_file"
+		echo "[pb]Error: file must be a \".tar.gz\" file"
+		echo "[pb]Error: $arch_file"
 		exit 1
 		;;
 	esac
 	file_present1 "$arch_file"
 elif test -n "$nl_src_dir"
 then
+	fix_path nl_src_dir
+	echo "[pb]Source directory \"${nl_src_dir}\" specified by user"
 	if test ! -d "$nl_src_dir"
 	then
-		echo "Error: directory $nl_src_dir not found"
+		echo "[pb]Error: directory $nl_src_dir not found"
 		exit 1
 	fi
 	if test ! -e "${nl_src_dir}/newlib/configure.host"
@@ -138,11 +156,12 @@ then
 		then
 			nl_src_dir="${nl_src_dir}/.."
 		else
-			echo "Error: file "${nl_src_dir}/newlib/configure.host" not found"
+			echo "[pb]Error: file "${nl_src_dir}/newlib/configure.host" not found"
 			exit 1
 		fi
 	fi
 else
+	echo "[pb]Searching for newlib sourche code..."
 	for pb_test in "$pb_cwd ${pb_cwd}/.. $pb_dir ${pb_dir}/.."
 	do
 		pb_test2=`ls -1d ${pb_test}/newlib-?.*/ 2>/dev/null`
@@ -170,7 +189,7 @@ else
 			fi
 			if test "$pb_test3" -ge 2
 			then
-				echo "Ambiguety: more than one archive present"
+				echo "[pb]Ambiguety: more than one archive present"
 				exit 1
 			fi
 		done
@@ -179,7 +198,7 @@ fi
 
 if test -z "$nl_src_dir" -a -z "$arch_file"
 then
-	echo "Newlib sourches not found"
+	echo "[pb]Newlib sourches not found!"
 	exit 1
 fi
 
@@ -187,7 +206,7 @@ change_dir()
 {
 	if ! cd $1
 	then
-		echo "Error: unable to cd $1"
+		echo "[pb]Error: unable to cd $1"
 		exit 1
 	fi
 }
@@ -196,19 +215,27 @@ make_dir()
 {
 	if test -d "$1"
 	then
-		echo "Warning: temporary directory $1 already exist"
+		echo "[pb]Warning: temporary directory $1 already exist"
 	else
-		if ! mkdir $1
+		if mkdir $1
 		then
-			echo "Unable to create directory $1"
+			echo "[pb]Directory $1 created"
+		else
+			echo "[pb]Unable to create directory $1"
 			exit 1
 		fi
 	fi
 }
 
 
-echo "Creating temporary directories"
-pb_tmpd="${pb_dir}/pb_tmp"
+echo "[pb]Creating temporary directories..."
+if test -z "$temp_dir"
+then
+	pb_tmpd="${pb_dir}/pb_tmp"
+else
+	pb_tmpd="${temp_dir}/pb_tmp"
+fi
+fix_path pb_tmpd
 make_dir $pb_tmpd
 pb_tnl="${pb_tmpd}/newlib-s"
 make_dir "$pb_tnl"
@@ -219,19 +246,19 @@ then
 	change_dir $pb_tnl
 	if tar -xzf $arch_file --strip-path=1
 	then
-		echo "newlib sourches extracted to $pb_tnl"
+		echo "[pb]newlib sourches extracted to $pb_tnl"
 		change_dir $pb_cwd
 	else
-		echo "Error: extraction failed!"
+		echo "[pb]Error: extraction failed!"
 		cd $pb_cwd
 		exit 1
 	fi
 else
 	if cp -r ${nl_src_dir}/* ${pb_tnl}/
 	then
-		echo "newlib sourches copied to $pb_tnl"
+		echo "[pb]newlib sourches copied to $pb_tnl"
 	else
-		echo "Error: copying failed!"
+		echo "[pb]Error: copying failed!"
 		exit 1
 	fi
 fi
@@ -244,9 +271,9 @@ file_present1 "${pb_tnl}/newlib/libc/include/stdlib.h"
 # apply port
 if cp -r ${pb_dir}/sys/* ${pb_tnl}/newlib/libc/sys
 then
-	echo "System specific files copied to newlib-s/newlib/libc/sys"
+	echo "[pb]System specific files copied to newlib-s/newlib/libc/sys"
 else
-	echo "Error: failed to copy files from ${pb_dir}/sys/"
+	echo "[pb]Error: failed to copy files from ${pb_dir}/sys/"
 	exit 1
 fi
 
@@ -254,17 +281,18 @@ patch_file()
 {
 	if patch -p0 <${pb_dir}/diffs/$1
 	then
-		echo "Diff applied to $2"
+		echo "[pb]Diff applied to $2"
 	else
-		echo "Error: patch failed!"
+		echo "[pb]Patch failed!"
 		cd $pb_cwd
-		exit 1
+		return 1
 	fi
+	return 0
 }
 
 change_dir $pb_tnl
-patch_file configure.diff configure.host
-patch_file config2.diff config.sub
+patch_file configure.diff configure.host || exit 1
+patch_file config2.diff config.sub || exit 1
 
 if [ $config_newlib == "no" ]
 then
@@ -283,9 +311,9 @@ then
 	ln -s /usr/bin/objdump ${pb_tmpd}/bin/${pb_target}-objdump && \
 	ln -s /usr/bin/ranlib ${pb_tmpd}/bin/${pb_target}-ranlib
 	then
-		echo "Links created in ${pb_tmpd}/bin"
+		echo "[pb]Links created in ${pb_tmpd}/bin"
 	else
-		echo "Error creating links"
+		echo "[pb]Error creating links"
 		exit 1
 	fi	
 	export PATH=${PATH}:${pb_tmpd}/bin
@@ -295,52 +323,55 @@ pb_tbld="${pb_tmpd}/tbld"
 make_dir $pb_tbld
 change_dir $pb_tbld
 
-build_newlib()
+config_newlib()
 {
-	echo "================================================="
-	echo "      *** RUNNIG CONFIGURATION SCRIPT: ***"
-	echo "================================================="
+	echo "[pb]================================================="
+	echo "[pb]      *** RUNNIG CONFIGURATION SCRIPT: ***"
+	echo "[pb]================================================="
 	
 	if ${pb_tnl}/configure --target=${pb_target} # --prefix=
 	then
-		echo "================================================="
-		echo "***Configuration script completed successfully***"
-		echo "================================================="
+		echo "[pb]================================================="
+		echo "[pb]***Configuration script completed successfully***"
+		echo "[pb]================================================="
 	else
-		echo "Error: configuration script failed"
+		echo "[pb]Error: configuration script failed"
 		exit 1
 	fi
-	
-	if [ $patch_makef == "yes" ]
-	then
-		patch_file $1 Makefile
-	fi
+}
 	
 	
 	
+make_newlib()
+{	
 	if [ "$make_newlib" == "no" ]
 	then
 		exit 0
 	fi
 	
-	echo "================================================="
-	echo "           *** RUNNING MAKE: ***"
-	echo "================================================="
+	echo "[pb]================================================="
+	echo "[pb]           *** RUNNING MAKE: ***"
+	echo "[pb]================================================="
 	
 	if make
 	then
-		echo "================================================="
-		echo "       ***make completed successfully***"
-		echo "================================================="
+		echo "[pb]================================================="
+		echo "[pb]       ***make completed successfully***"
+		echo "[pb]================================================="
 	
 	else
-		echo "Error: make failed"
+		echo "[pb]Error: make failed"
 		exit 1
 	fi
 
 }
 
-build_newlib mkf1.diff
+config_newlib
+if [ $patch_makef == "yes" ]
+then
+	patch_file mkf1.diff Makefile || exit 1
+fi
+make_newlib
 
 file_present1 ${pb_tbld}/${pb_target}/newlib/libc.a
 file_present1 ${pb_tbld}/${pb_target}/newlib/libg.a
@@ -353,17 +384,19 @@ then
 	dest_dir=${pb_dir}
 fi
 
+fix_path dest_dir
+
 if ! mkdir -p ${dest_dir}/lib
 then
-	echo "Error: failed to created directory ${dest_dir}/lib"
+	echo "[pb]Error: failed to created directory ${dest_dir}/lib"
 	exit 1
 fi
 
 if cp ${pb_tbld}/${pb_target}/newlib/lib*.a ${dest_dir}/lib
 then
-	echo "Library files copied to ${dest_dir}/lib"
+	echo "[pb]Library files copied to ${dest_dir}/lib"
 else
-	echo "Error: failed to copy files to ${dest_dir}/lib"
+	echo "[pb]Error: failed to copy files to ${dest_dir}/lib"
 	exit 1
 fi
 
@@ -371,9 +404,9 @@ make_dir ${dest_dir}/include
 
 if cp -r ${pb_tnl}/newlib/libc/include/* ${dest_dir}/include && cp -r ${pb_dir}/sys/fd32/include/* ${dest_dir}/include
 then
-	echo "Header files copied to ${dest_dir}/include"
+	echo "[pb]Header files copied to ${dest_dir}/include"
 else
-	echo "Error: failed to copy files to ${dest_dir}/include"
+	echo "[pb]Error: failed to copy files to ${dest_dir}/include"
 	exit 1
 fi
 
@@ -384,32 +417,22 @@ fi
 
 if [ $second_pass == "yes" ]
 then
-	echo "Patching Makefile and executing make again"
+	echo "[pb]Patching Makefile and executing make again..."
 	pb_tbld2="${pb_tmpd}/tbld2"
 	make_dir $pb_tbld2
 	change_dir $pb_tbld2
-	#rm -rf ${pb_tbld}/${pb_target}/*
-	patch_makef="yes"
-	#change_dir $pb_tbld
-	build_newlib mkf2.diff
-	#if ! make clean
-	#then
-	#	"Error: \"make clean\" failed"
-	#	exit 1
-	#fi
-	#patch_file mkf2.diff Makefile
-	#if make
-	#then
-	#	echo "make completed successfully"
-	#else
-	#	echo "Error: make failed"
-	#	exit 1
-	#fi
+	config_newlib
+	if ! patch_file mkf2.diff
+	then
+		echo "[pb]Trying sed instead..."
+		sed 's/ -g / /g' <Makefile >Makefile || exit 1
+	fi
+	make_newlib
 	if cp ${pb_tbld2}/${pb_target}/newlib/libc.a ${dest_dir}/lib
 	then
-		echo "New libc.a copied to ${dest_dir}/lib"
+		echo "[pb]New libc.a copied to ${dest_dir}/lib"
 	else
-		echo "Error: failed to copy libc.a to ${dest_dir}/lib"
+		echo "[pb]Error: failed to copy libc.a to ${dest_dir}/lib"
 		exit 1
 	fi
 fi
